version: "3.8"
services:
  service_a:
    build: ./service-a
    ports:
      - "8081:8081"
    depends_on:
      - service_b
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    networks:
      - example

  service_b:
    build: ./service-b
    ports:
      - "8082:8082"
    environment:
      - WEATHER_API_KEY=ed40a91acbbe4226b7535827241311
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    networks:
      - example

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "4317:4317" # Porta para o protocolo OTLP (gRPC)
      - "4318:4318" # Porta OTLP (HTTP)
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    command:
      --config=/etc/otel-collector-config.yml
    networks:
      - example

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - example

networks:
  example: